In [1]:
from utils import *
import json
import random
import pandas as pd
import numpy as np
import torch as th


class Args:
    data_frac = 0.3
    min_user_freq = 10
    min_book_freq = 10
    max_user_freq = 200
    train_frac = 0.95
    his_len = 100
    n_neg = 10


args = Args()


In [16]:
test_samples = pkl_read('data/test_samples.pkl', None)

In [13]:
i = 4
j = 2
dim = 2

w = th.empty(i, j, dim, dim)
th.nn.init.normal_(w)
#print(w)

batch_size = 4
vecs = th.empty(batch_size, i, dim)
th.nn.init.normal_(vecs)
#print(vecs)

batch 0
cap 0
tensor([0.7386, 0.0402])
tensor([ 2.0551, -0.7286])
cap 1
tensor([0.4266, 0.6307])
tensor([0.6234, 0.3287])
cap 2
tensor([0.5516, 1.4071])
tensor([-0.5060, -0.9031])
cap 3
tensor([0.7027, 1.4347])
tensor([-1.5141, -1.8416])
batch 1
cap 0
tensor([-0.8517,  1.0983])
tensor([-0.5928,  0.0627])
cap 1
tensor([0.7751, 0.9237])
tensor([0.9809, 0.6060])
cap 2
tensor([0.9317, 1.8818])
tensor([-0.8118, -1.0031])
cap 3
tensor([-5.2061, -1.5969])
tensor([-5.8053,  1.6262])


In [ ]:

# batch 0
print("batch 0")
print("cap 0")
# vec 0, out 0
print(th.matmul(vecs[0][0], w[0][0]))
# vec 0, out 1
print(th.matmul(vecs[0][0], w[0][1]))
print("cap 1")
# vec 1, out 0
print(th.matmul(vecs[0][1], w[1][0]))
# vec 1, out 1
print(th.matmul(vecs[0][1], w[1][1]))
print("cap 2")
# vec 2, out 0
print(th.matmul(vecs[0][2], w[2][0]))
# vec 2, out 1
print(th.matmul(vecs[0][2], w[2][1]))
print("cap 3")
# vec 3, out 0
print(th.matmul(vecs[0][3], w[3][0]))
# vec 3, out 1
print(th.matmul(vecs[0][3], w[3][1]))


# desired output
# batch 1
print("batch 1")
print("cap 0")
# vec 0, out 0
print(th.matmul(vecs[1][0], w[0][0]))
# vec 0, out 1
print(th.matmul(vecs[1][0], w[0][1]))
print("cap 1")
# vec 1, out 0
print(th.matmul(vecs[1][1], w[1][0]))
# vec 1, out 1
print(th.matmul(vecs[1][1], w[1][1]))
print("cap 2")
# vec 2, out 0
print(th.matmul(vecs[1][2], w[2][0]))
# vec 2, out 1
print(th.matmul(vecs[1][2], w[2][1]))
print("cap 3")
# vec 3, out 0
print(th.matmul(vecs[1][3], w[3][0]))
# vec 3, out 1
print(th.matmul(vecs[1][3], w[3][1]))